# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 223f04dbb6976e4866fe362670ea65c94affb0080eeb008b21d7c5725f379188f2dd872b4cf21e73237d542a82c4b78c35abbf44de39dc2c8719d9073389c8c1

test:
  secret_key_base: e7fecf872df6783a31974a40ccc05ba039cfb72cee153df9dc00f76d821dc8b81813169876b86fe1474990e34ea48c771759cd16c9b3da636f1cb49bd742e971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
